spring.application.name=payment
server.port=${SERVER_PORT:8084}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices}?currentSchema=payment
spring.datasource.username=${DB_USER:payment_user}
spring.datasource.password=${DB_PASSWORD:payment_pass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.schemas=payment
spring.flyway.default-schema=payment

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
